global:
  scrape_interval: 15s
  scrape_timeout: 15s
  evaluation_interval: 2m
  external_labels:
    monitor: 'codelab-monitor'
  query_log_file: /prometheus/data/query_log_file.log
rule_files:
  - "rule.yml"
scrape_configs:
  - job_name: "app-server"
    metrics_path: "/actuator/prometheus"
    scheme: 'http'
    scrape_interval: 5s
    static_configs:
      - targets:
          - "app:8082"
